version: '3'

tasks:
  build:
    dir: ./cmd

    cmds:
      - rm ../build/bin/mock-server
      - CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o ../build/bin/mock-server .

  test:
    deps: [build]
    cmds:
      - go test -v -count=1 ./test/...


